# serverless.yml

service: my-express-application
	
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: index.handler
    timeout: 60
    memorySize: 1024
    reservedConcurrency: 10
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'